<?php

namespace App\Services;

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use Symfony\Component\Process\Process;

class ChatServiceClient
{
    private string $baseUrl;
    private string $internalKey;

    public function __construct()
    {
        $this->baseUrl     = rtrim(config('services.chat_url', 'http://chat-nginx'), '/');
        $this->internalKey = config('services.internal_key', '');
    }

    public function appendMessage(string $sessionId, string $userId, string $role, string $content, array $usage = [], array $attachmentIds = []): void
    {
        try {
            Http::timeout(15)
                ->withHeaders(['X-Internal-Service-Key' => $this->internalKey, 'Accept-Encoding' => 'identity'])
                ->post("{$this->baseUrl}/api/internal/sessions/{$sessionId}/messages", array_merge([
                    'user_id' => $userId,
                    'role'    => $role,
                    'content' => $content,
                    ...(! empty($attachmentIds) ? ['attachment_ids' => $attachmentIds] : []),
                ], $usage));
        } catch (\Exception $e) {
            // Persistence failure shouldn't fail an already-completed chat response —
            // the user already has their answer. Just log it for later investigation.
            Log::error('ChatServiceClient::appendMessage failed', ['error' => $e->getMessage(), 'session_id' => $sessionId]);
        }
    }

    /**
     * @param string[] $ids
     * @return array<int, array{id: string, mime_type: string, original_name: string, base64?: string, extracted_text?: string}>
     */
    public function resolveAttachments(array $ids): array
    {
        if (empty($ids)) {
            return [];
        }

        try {
            // Accept-Encoding: identity — same-host docker traffic gains nothing from
            // compression, and forcing it off sidesteps a real bug confirmed live: under
            // this service's Swoole coroutine hooks (config/octane.php's hook_flags,
            // needed for ChatController::compare()'s concurrent fan-out), Guzzle's
            // automatic Brotli decompression silently fails on a hooked connection —
            // chat-service's response comes back Content-Encoding: br (large enough
            // payloads like extracted_text cross its compression threshold), the client
            // reports success with the marker header renamed but never actually inflates
            // the body, and the caller sees an empty/garbled result with no exception and
            // no error logged. Confirmed via a raw `curl --compressed` against the same
            // endpoint: it decodes br cleanly, so this is specific to the hooked client,
            // not the response itself.
            $response = Http::timeout(20)
                ->withHeaders(['X-Internal-Service-Key' => $this->internalKey, 'Accept-Encoding' => 'identity'])
                ->post("{$this->baseUrl}/api/internal/attachments/resolve", ['ids' => $ids]);

            return $response->successful() ? ($response->json('attachments') ?? []) : [];
        } catch (\Exception $e) {
            Log::error('ChatServiceClient::resolveAttachments failed', ['error' => $e->getMessage()]);
            return [];
        }
    }

    /**
     * Documents (not images — see chat-service's own comment on that) previously
     * uploaded anywhere in this session, re-extracted fresh from storage. Called only
     * when the current turn has no attachments of its own, so a follow-up like "keep
     * the same structure" can still see a file uploaded on an earlier turn instead of
     * the model claiming it has no access to something the UI still shows attached.
     *
     * @return array<int, array{id: string, original_name: string, extracted_text: string}>
     */
    public function getSessionAttachments(string $sessionId): array
    {
        try {
            $response = Http::timeout(20)
                ->withHeaders(['X-Internal-Service-Key' => $this->internalKey, 'Accept-Encoding' => 'identity'])
                ->get("{$this->baseUrl}/api/internal/sessions/{$sessionId}/attachments");

            return $response->successful() ? ($response->json('attachments') ?? []) : [];
        } catch (\Exception $e) {
            Log::error('ChatServiceClient::getSessionAttachments failed', ['error' => $e->getMessage(), 'session_id' => $sessionId]);
            return [];
        }
    }

    /**
     * Uploads AI-generated bytes (an image, a generated spreadsheet/deck/PDF) as a
     * real file_attachments row, the same way a user's own upload would be stored —
     * see ChatInternalController::createAttachmentFromBytes() for the mirrored logic.
     * Returns the new attachment's id, or null on any failure (a failed upload
     * shouldn't break an otherwise-successful chat reply; callers should just omit
     * the attachment rather than fail the whole response).
     */
    public function createAttachmentFromBytes(string $userId, string $filename, string $mimeType, string $rawBytes): ?string
    {
        // Shells out to the real `curl` binary instead of Laravel's Http:: facade.
        // Confirmed live, methodically: neither a base64-string JSON body nor a
        // proper Guzzle multipart upload could get a real generated image (a few
        // hundred KB to several MB) to chat-service — both failed identically with
        // "cURL error 0 ... unable to rewind the body of the request" the moment a
        // retry was attempted mid-transfer. Raising Swoole's package_max_length
        // (config/octane.php) didn't fix it either. Then proved the server side was
        // never the problem at all: the exact same multipart upload via a raw `curl`
        // process (not PHP) against this same endpoint succeeded instantly, first
        // try, at 3MB. So the failure is specific to PHP/Guzzle's own cURL bindings
        // in THIS service — which runs under Octane/Swoole with SWOOLE_HOOK_ALL
        // (needed for ChatController::compare()'s concurrent fan-out). Swoole's
        // coroutine hooking of PHP's socket/cURL functions already caused one other
        // silent Guzzle incompatibility this session (Brotli decompression); this
        // reads as the same class of bug surfacing differently for large bodies. A
        // real `curl` subprocess is entirely outside Swoole's hook scope — hooks
        // only intercept this PHP process's own calls, never a child OS process it
        // spawns — so it sidesteps the bug rather than needing to keep chasing it.
        $tmpPath = tempnam(sys_get_temp_dir(), 'upload_');
        file_put_contents($tmpPath, $rawBytes);

        try {
            $process = new Process([
                'curl', '-sS', '--max-time', '60',
                '-H', "X-Internal-Service-Key: {$this->internalKey}",
                '-H', 'Accept-Encoding: identity',
                '-F', "user_id={$userId}",
                '-F', "mime_type={$mimeType}",
                '-F', "file=@{$tmpPath};filename=".basename($filename).";type={$mimeType}",
                "{$this->baseUrl}/api/internal/attachments/create-from-bytes",
            ]);
            $process->run();

            if (! $process->isSuccessful()) {
                Log::error('ChatServiceClient::createAttachmentFromBytes failed', [
                    'error' => $process->getErrorOutput() ?: $process->getOutput(),
                ]);
                return null;
            }

            $data = json_decode($process->getOutput(), true);

            return $data['attachment']['id'] ?? null;
        } catch (\Exception $e) {
            Log::error('ChatServiceClient::createAttachmentFromBytes failed', ['error' => $e->getMessage()]);
            return null;
        } finally {
            @unlink($tmpPath);
        }
    }
}
