import { LegalPageShell } from '@/components/legal/LegalPageShell'

export default function TermsPage() {
  return (
    <LegalPageShell title="Terms of Service" updated="August 31, 2026">
      <p>
        These Terms of Service (&quot;Terms&quot;) govern your use of Alveta.ai. By creating an account or
        using the platform, you agree to these Terms.
      </p>

      <h2>1. The Service</h2>
      <p>
        Alveta.ai gives you access to AI chat models from multiple third-party providers through a single
        account, wallet, and subscription. Model availability, pricing, and capabilities may change over
        time as providers update their own offerings.
      </p>

      <h2>2. Your Account</h2>
      <p>
        You&apos;re responsible for keeping your login credentials secure and for all activity under your
        account. You must be able to form a binding contract to use the service, and you must provide
        accurate account information.
      </p>

      <h2>3. Acceptable Use</h2>
      <p>You agree not to use the platform to:</p>
      <ul>
        <li>Generate content that is illegal, harmful, or violates another party&apos;s rights.</li>
        <li>Attempt to bypass usage limits, security controls, or the malware scanning applied to uploads.</li>
        <li>Resell or redistribute access to the platform without our written permission.</li>
      </ul>

      <h2>4. Subscriptions, Wallet, and Billing</h2>
      <p>
        Paid plans are billed on a recurring basis through our payment processor. Wallet credit is used to
        pay for AI usage and is not a substitute for subscription payment. Upgrading a plan charges the new
        plan&apos;s price immediately; downgrading takes effect at your next renewal so you keep your
        current plan&apos;s access until then.
      </p>

      <h2>5. Intellectual Property</h2>
      <p>
        You retain ownership of the content you submit. Responses generated by AI models are provided
        &quot;as is&quot; — you are responsible for reviewing AI-generated content before relying on it,
        as it may be inaccurate or incomplete.
      </p>

      <h2>6. Limitation of Liability</h2>
      <p>
        The service is provided on an &quot;as available&quot; basis. To the maximum extent permitted by
        law, Alveta.ai is not liable for indirect, incidental, or consequential damages arising from your
        use of the platform, including reliance on AI-generated output.
      </p>

      <h2>7. Termination</h2>
      <p>
        You may stop using the service and cancel your subscription at any time. We may suspend or
        terminate accounts that violate these Terms.
      </p>

      <h2>8. Changes to These Terms</h2>
      <p>
        We may update these Terms from time to time. Continued use of the platform after a change
        constitutes acceptance of the updated Terms.
      </p>

      <h2>9. Contact</h2>
      <p>Questions about these Terms can be sent to our support team through the app.</p>
    </LegalPageShell>
  )
}
